#!/bin/bash

set -e

DISTRO=$(lsb_release -si)
if ! id -u nimbus > /dev/null 2>&1; then
  case $DISTRO in
    Ubuntu|Debian)
      adduser --system --no-create-home --group nimbus
      ;;
    Fedora)
      adduser --system --no-create-home --user-group nimbus
      ;;
    *) # blind shot... ToDo: add more DISTRO cases here
      adduser --system --no-create-home --group nimbus
      ;;
  esac
fi

chown nimbus:nimbus /var/lib/nimbus

dialog_network() {
  exec 3>&1

  NETWORK_DIALOG=(dialog --keep-tite --title "Eth2 Network" --menu "Select Eth2 Network for Nimbus:" 22 76 16)
  OPTIONS=(mainnet "Mainnet"
    pyrmont "Pyrmont Testnet"
    prater "Prater Testnet"
  )
  NETWORK=$("${NETWORK_DIALOG[@]}" "${OPTIONS[@]}" 2>&1 >/dev/tty)
}

WEB3_HELP="To monitor the Eth1 validator deposit contract, you'll need to pair the Nimbus beacon node with a Web3 provider capable of serving Eth1 event logs. This could be a locally running Eth1 client such as Geth or a cloud service such as Infura. For more information please see our setup guides:

https://status-im.github.io/nimbus-eth2/eth1.html

Note: please make sure the provider is compatible with the selected Eth2 Network."

dialog_web3_provider() {
  exec 3>&1

  WEB3_URL=$(dialog --title "Eth1 Web3 Provider" \
    --clear \
    --inputbox "${WEB3_HELP}" 20 110 2>&1 1>&3)

  # check for empty Web3 Provider
  if [ -z $WEB3_URL ]; then
    echo "You didn't provide any Eth1 Web3 Provider.
You should fix this by editing /usr/lib/systemd/system/nimbus.service and setting proper value on WEB3_URL."
  fi

  # check for Web3 Provider URL prefixes (https:// or wss://)
  if [[ !( -z $WEB3_URL ) && !( $WEB3_URL =~ ^http\:\/\/.* || $WEB3_URL =~ ^https\:\/\/.* || $WEB3_URL =~ ^ws\:\/\/.* || $WEB3_URL =~ ^wss\:\/\/.* ) ]]; then
    echo "You provided an invalid Eth1 Web3 Provider. This might lead to unexpected behavior on Nimbus.
You should fix this by editing /usr/lib/systemd/system/nimbus.service and setting proper value on WEB3_URL"
  fi
}

if [[ -z $NETWORK || !( $NETWORK == "mainnet" || $NETWORK == "pyrmont" || $NETWORK == "prater" ) ]]; then
  case $DISTRO in
    Fedora) # RPM doesn't accept interactive scripts. ToDo: add more RPM-based distros to this list.
      echo "You didn't provide any valid NETWORK."
      echo "You should fix this by editing /usr/lib/systemd/system/nimbus.service and setting proper value on NETWORK."
      ;;
    *)
      dialog_network
      ;;
  esac
fi

if [ -z $WEB3_URL ]; then
  case $DISTRO in
    Fedora) # RPM doesn't accept interactive scripts. ToDo: add more RPM-based distros to this list.
      echo $WEB3_HELP
      echo "You didn't provide any valid WEB3_URL."
      echo "You should fix this by editing /usr/lib/systemd/system/nimbus.service and setting proper value on WEB3_URL."
      ;;
  *)
    dialog_web3_provider
    ;;
  esac
fi

echo "Environment=NETWORK=${NETWORK}" >>/usr/lib/systemd/system/nimbus.service
echo "Environment=WEB3_URL=${WEB3_URL}" >>/usr/lib/systemd/system/nimbus.service