#!/bin/sh

set -e

rm -rf /var/lib/nimbus
rm -rf /usr/lib/systemd/system/nimbus.service

if [ `sed -n "/^nimbus/p" /etc/passwd` ]; then
  userdel nimbus # userdel will also delete the nimbus group
fi

