# beacon_chain
# Copyright (c) 2021-2025 Status Research & Development GmbH
# Licensed and distributed under either of
#   * MIT license (license terms in the root directory or at https://opensource.org/licenses/MIT).
#   * Apache v2 license (license terms in the root directory or at https://www.apache.org/licenses/LICENSE-2.0).
# at your option. This file may not be copied, modified, or distributed except according to those terms.

{.push raises: [].}
{.used.}

import
  unittest2,
  ./testutil,
  ../beacon_chain/spec/[forks, network]

from ../beacon_chain/spec/presets import RuntimeConfig

type TargetFork {.pure.} = enum
  Capella
  Deneb
  Electra
  Fulu
  BPO1

template checkTargetGossipState(
    targetEpoch, denebForkEpoch, electraForkEpoch, fuluForkEpoch,
    bpo1ForkEpoch: int, isBehind: bool, targetForks: set[TargetFork]):
    auto =
  var targetGossipState: GossipState
  for targetFork in targetForks:
    case targetFork
    of TargetFork.Capella: targetGossipState.incl GENESIS_EPOCH
    of TargetFork.Deneb: targetGossipState.incl denebForkEpoch.Epoch
    of TargetFork.Electra: targetGossipState.incl electraForkEpoch.Epoch
    of TargetFork.Fulu: targetGossipState.incl fuluForkEpoch.Epoch
    of TargetFork.BPO1: targetGossipState.incl bpo1ForkEpoch.Epoch
  getTargetGossipState(
    targetEpoch.Epoch,
    RuntimeConfig(
      ALTAIR_FORK_EPOCH: GENESIS_EPOCH, BELLATRIX_FORK_EPOCH: GENESIS_EPOCH,
      CAPELLA_FORK_EPOCH: GENESIS_EPOCH,
      DENEB_FORK_EPOCH: denebForkEpoch.Epoch,
      ELECTRA_FORK_EPOCH: electraForkEpoch.Epoch,
      FULU_FORK_EPOCH: fuluForkEpoch.Epoch,
      BLOB_SCHEDULE: @[BlobParameters(EPOCH: bpo1ForkEpoch.Epoch)]), isBehind) == targetGossipState

suite "Gossip fork transition":
  test "Gossip fork transition":
    check:
      checkTargetGossipState( 5,  0,  1,  8, 11, false, {TargetFork.Electra})
      checkTargetGossipState( 1,  4,  7,  9, 11,  true, default(set[TargetFork]))
      checkTargetGossipState( 3,  0,  5,  6, 10, false, {TargetFork.Deneb})
      checkTargetGossipState(11,  2,  6, 10, 11, false, {TargetFork.BPO1})
      checkTargetGossipState( 8,  4,  6, 10, 11, false, {TargetFork.Electra})
      checkTargetGossipState( 9,  2,  4,  9, 11, false, {TargetFork.Fulu})
      checkTargetGossipState( 7,  2,  3,  5, 11, false, {TargetFork.Fulu})
      checkTargetGossipState( 9,  0,  4,  8,  9, false, {TargetFork.BPO1})
      checkTargetGossipState( 7,  1,  2,  3, 10, false, {TargetFork.Fulu})
      checkTargetGossipState(11,  3,  4,  5, 11, false, {TargetFork.BPO1})
      checkTargetGossipState( 0,  0,  1,  2,  3,  true, default(set[TargetFork]))
      checkTargetGossipState(10,  0,  6,  7,  9, false, {TargetFork.BPO1})
      checkTargetGossipState( 5,  1,  3,  4,  7, false, {TargetFork.Fulu})
      checkTargetGossipState( 0,  3,  7, 10, 11, false, {TargetFork.Capella})
      checkTargetGossipState(10,  0,  5,  8, 11, false, {TargetFork.Fulu,   TargetFork.BPO1})
      checkTargetGossipState( 8,  1,  3,  6, 10, false, {TargetFork.Fulu})
      checkTargetGossipState( 6,  1,  4, 10, 11, false, {TargetFork.Electra})
      checkTargetGossipState( 3,  0,  5,  7,  8, false, {TargetFork.Deneb})
      checkTargetGossipState( 3,  2,  3,  4,  7, false, {TargetFork.Electra,     TargetFork.Fulu})
      checkTargetGossipState( 4,  3,  6,  7,  8, false, {TargetFork.Deneb})
      checkTargetGossipState( 8,  2,  6,  7,  9, false, {TargetFork.Fulu,   TargetFork.BPO1})
      checkTargetGossipState(11,  1,  5,  7,  9, false, {TargetFork.BPO1})
      checkTargetGossipState( 9,  1,  2,  7, 10,  true, default(set[TargetFork]))
      checkTargetGossipState( 2,  1,  2,  3,  9, false, {TargetFork.Electra,     TargetFork.Fulu})
      checkTargetGossipState( 4,  0,  4,  8, 11, false, {TargetFork.Electra})
      checkTargetGossipState( 4,  4,  5,  7,  9, false, {TargetFork.Deneb,   TargetFork.Electra})
      checkTargetGossipState( 8,  0,  0,  4,  7, false, {TargetFork.BPO1})
      checkTargetGossipState( 6,  5,  7,  8, 10, false, {TargetFork.Deneb,   TargetFork.Electra})
      checkTargetGossipState( 6,  0,  2, 10, 11, false, {TargetFork.Electra})
      checkTargetGossipState( 2,  1,  2, 10, 11, false, {TargetFork.Electra})
      checkTargetGossipState( 5,  0,  2,  3,  6, false, {TargetFork.Fulu,   TargetFork.BPO1})
      checkTargetGossipState( 2,  2,  6,  8, 11, false, {TargetFork.Deneb})
      checkTargetGossipState(10,  0,  6,  8, 11, false, {TargetFork.Fulu,   TargetFork.BPO1})
      checkTargetGossipState( 8,  0,  0,  2,  3,  true, default(set[TargetFork]))
      checkTargetGossipState( 4,  3,  7,  8,  9,  true, default(set[TargetFork]))
      checkTargetGossipState( 0,  0,  2,  5, 10, false, {TargetFork.Deneb})
      checkTargetGossipState( 1,  3,  4,  5,  9, false, {TargetFork.Capella})
      checkTargetGossipState( 5,  2,  6,  8, 10, false, {TargetFork.Deneb,   TargetFork.Electra})
      checkTargetGossipState( 7,  0,  1,  4, 11, false, {TargetFork.Fulu})
      checkTargetGossipState( 3,  2,  3,  9, 10, false, {TargetFork.Electra})
      checkTargetGossipState( 8,  3,  5,  9, 11,  true, default(set[TargetFork]))
      checkTargetGossipState( 9,  3,  6,  7,  8, false, {TargetFork.BPO1})
      checkTargetGossipState( 0,  1,  2,  8,  9, false, {TargetFork.Capella, TargetFork.Deneb})
      checkTargetGossipState( 6,  2,  7,  8, 11, false, {TargetFork.Deneb,   TargetFork.Electra})
      checkTargetGossipState( 2,  3,  4,  6,  7, false, {TargetFork.Capella, TargetFork.Deneb})
      checkTargetGossipState( 1,  3,  5,  8, 10, false, {TargetFork.Capella})
      checkTargetGossipState( 1,  2,  5,  8, 10,  true, default(set[TargetFork]))
      checkTargetGossipState( 9,  4,  5,  7,  9, false, {TargetFork.BPO1})
      checkTargetGossipState(11,  0,  5,  9, 10, false, {TargetFork.BPO1})
      checkTargetGossipState( 0,  1,  5,  7,  9, false, {TargetFork.Capella, TargetFork.Deneb})
      checkTargetGossipState( 0,  2,  6,  8, 10,  true, default(set[TargetFork]))
      checkTargetGossipState( 8,  0,  5,  8, 11, false, {TargetFork.Fulu})
      checkTargetGossipState( 7,  4,  7, 10, 11, false, {TargetFork.Electra})
      checkTargetGossipState( 6,  2,  3,  5,  7, false, {TargetFork.Fulu,   TargetFork.BPO1})
      checkTargetGossipState(11,  0,  1,  3,  7, false, {TargetFork.BPO1})
      checkTargetGossipState( 6,  5,  6,  8,  9, false, {TargetFork.Electra})
      checkTargetGossipState( 1,  2,  5,  8, 11, false, {TargetFork.Capella, TargetFork.Deneb})
      checkTargetGossipState(11,  1,  5,  9, 11, false, {TargetFork.BPO1})
      checkTargetGossipState( 9,  3,  6,  7,  9, false, {TargetFork.BPO1})
      checkTargetGossipState( 3,  0,  1,  6,  8, false, {TargetFork.Electra})
      checkTargetGossipState( 5,  1,  6,  8, 10, false, {TargetFork.Deneb,   TargetFork.Electra})
      checkTargetGossipState( 5,  2,  3,  8, 11, false, {TargetFork.Electra})
      checkTargetGossipState( 4,  2,  8,  9, 10, false, {TargetFork.Deneb})
      checkTargetGossipState( 3,  1,  3,  4,  5, false, {TargetFork.Electra,     TargetFork.Fulu})
      checkTargetGossipState(11,  2,  7, 10, 11, false, {TargetFork.BPO1})
      checkTargetGossipState(10,  3,  5, 10, 11, false, {TargetFork.Fulu,   TargetFork.BPO1})
      checkTargetGossipState( 5,  2,  6,  8, 11, false, {TargetFork.Deneb,   TargetFork.Electra})
      checkTargetGossipState( 4,  2,  6,  8, 11, false, {TargetFork.Deneb})
      checkTargetGossipState( 2,  0,  1,  4, 11, false, {TargetFork.Electra})
      checkTargetGossipState( 1,  1,  4,  6, 10,  true, default(set[TargetFork]))
      checkTargetGossipState( 4,  0,  6,  7, 10, false, {TargetFork.Deneb})
      checkTargetGossipState( 7,  3,  4,  7,  8,  true, default(set[TargetFork]))
      checkTargetGossipState( 1,  0,  0,  6,  8, false, {TargetFork.Electra})
      checkTargetGossipState( 2,  1,  3,  6, 10,  true, default(set[TargetFork]))
      checkTargetGossipState( 7,  2,  3,  7,  8, false, {TargetFork.Fulu,   TargetFork.BPO1})
      checkTargetGossipState( 3,  2,  4,  5, 11, false, {TargetFork.Deneb,   TargetFork.Electra})
      checkTargetGossipState( 1,  4,  5,  7,  8, false, {TargetFork.Capella})
      checkTargetGossipState( 1,  3,  7,  8, 10, false, {TargetFork.Capella})
      checkTargetGossipState( 8,  0,  1,  6, 10, false, {TargetFork.Fulu})
      checkTargetGossipState( 7,  1,  5,  7, 11, false, {TargetFork.Fulu})
      checkTargetGossipState( 1,  6,  8, 10, 11, false, {TargetFork.Capella})
      checkTargetGossipState( 0,  1,  2,  3,  7, false, {TargetFork.Capella, TargetFork.Deneb})
      checkTargetGossipState(11,  2,  4,  5,  8, false, {TargetFork.BPO1})
      checkTargetGossipState( 6,  1,  5,  7,  9, false, {TargetFork.Electra,     TargetFork.Fulu})
      checkTargetGossipState( 7,  0,  3,  5, 11, false, {TargetFork.Fulu})
      checkTargetGossipState( 6,  0,  3,  9, 10, false, {TargetFork.Electra})
      checkTargetGossipState( 8,  2,  7,  8, 10, false, {TargetFork.Fulu})
      checkTargetGossipState( 7,  3,  5,  6,  9, false, {TargetFork.Fulu})
      checkTargetGossipState( 8,  0,  4,  7, 11, false, {TargetFork.Fulu})
      checkTargetGossipState( 8,  0,  3,  8, 11, false, {TargetFork.Fulu})
      checkTargetGossipState( 4,  1,  2,  4,  6, false, {TargetFork.Fulu})
      checkTargetGossipState(10,  0,  2,  4, 11, false, {TargetFork.Fulu,   TargetFork.BPO1})
      checkTargetGossipState( 1,  0,  2,  7, 11, false, {TargetFork.Deneb,   TargetFork.Electra})
      checkTargetGossipState( 6,  1,  2,  5,  7, false, {TargetFork.Fulu,   TargetFork.BPO1})
      checkTargetGossipState(10,  0,  1,  8,  9, false, {TargetFork.BPO1})
      checkTargetGossipState( 0,  1,  3,  4,  5,  true, default(set[TargetFork]))
      checkTargetGossipState(11,  0,  2,  9, 10, false, {TargetFork.BPO1})
      checkTargetGossipState( 7,  2,  7,  8,  9, false, {TargetFork.Electra,     TargetFork.Fulu})
      checkTargetGossipState( 0,  0,  5,  6,  9, false, {TargetFork.Deneb})
      checkTargetGossipState( 4,  2,  6,  8,  9, false, {TargetFork.Deneb})
      checkTargetGossipState( 2,  2,  6,  7,  8, false, {TargetFork.Deneb})
      checkTargetGossipState(11,  2,  8,  9, 10,  true, default(set[TargetFork]))
      checkTargetGossipState( 8,  1,  2,  8, 11, false, {TargetFork.Fulu})
      checkTargetGossipState( 7,  0,  1,  2,  8, false, {TargetFork.Fulu,   TargetFork.BPO1})
      checkTargetGossipState( 7,  0,  1,  8,  9, false, {TargetFork.Electra,     TargetFork.Fulu})
      checkTargetGossipState( 3,  1,  7,  9, 10, false, {TargetFork.Deneb})
      checkTargetGossipState( 6,  2,  6,  7, 11, false, {TargetFork.Electra,     TargetFork.Fulu})
      checkTargetGossipState( 2,  3,  5,  7, 10, false, {TargetFork.Capella, TargetFork.Deneb})
      checkTargetGossipState(10,  4,  5,  7,  9, false, {TargetFork.BPO1})
      checkTargetGossipState( 8,  1,  4,  5,  8, false, {TargetFork.BPO1})
      checkTargetGossipState( 9,  0,  2,  7, 10, false, {TargetFork.Fulu,   TargetFork.BPO1})
      checkTargetGossipState( 8,  1,  5,  7,  8, false, {TargetFork.BPO1})
      checkTargetGossipState( 8,  1,  3,  7,  9, false, {TargetFork.Fulu,   TargetFork.BPO1})
      checkTargetGossipState( 4,  0,  3,  4, 11, false, {TargetFork.Fulu})
      checkTargetGossipState( 0,  1,  5,  9, 10, false, {TargetFork.Capella, TargetFork.Deneb})
      checkTargetGossipState( 3,  4,  6,  7,  8, false, {TargetFork.Capella, TargetFork.Deneb})
      checkTargetGossipState(11,  4,  5,  6, 10, false, {TargetFork.BPO1})
      checkTargetGossipState( 4,  2,  4,  9, 10, false, {TargetFork.Electra})
      checkTargetGossipState(11,  0,  3,  5,  7, false, {TargetFork.BPO1})
      checkTargetGossipState( 9,  0,  3,  7, 11, false, {TargetFork.Fulu})
      checkTargetGossipState(11,  1,  7,  8, 11, false, {TargetFork.BPO1})
      checkTargetGossipState( 0,  0,  1,  3,  4, false, {TargetFork.Deneb,   TargetFork.Electra})
      checkTargetGossipState( 3,  4,  5,  7,  9, false, {TargetFork.Capella, TargetFork.Deneb})
      checkTargetGossipState(10,  3,  6,  8,  9,  true, default(set[TargetFork]))
      checkTargetGossipState( 6,  7,  9, 10, 11, false, {TargetFork.Capella, TargetFork.Deneb})
      checkTargetGossipState( 7,  2,  4,  5,  7, false, {TargetFork.BPO1})
      checkTargetGossipState( 9,  0,  0,  6, 11, false, {TargetFork.Fulu})
      checkTargetGossipState( 4,  2,  3,  7, 10,  true, default(set[TargetFork]))
      checkTargetGossipState( 3,  0,  2,  3,  5, false, {TargetFork.Fulu})
      checkTargetGossipState(10,  4,  6,  7,  8, false, {TargetFork.BPO1})
      checkTargetGossipState( 1,  2,  6,  9, 11,  true, default(set[TargetFork]))
      checkTargetGossipState( 7,  0,  1,  3,  7, false, {TargetFork.BPO1})
      checkTargetGossipState( 9,  0,  6,  8, 11,  true, default(set[TargetFork]))
      checkTargetGossipState( 6,  2,  4, 10, 11, false, {TargetFork.Electra})
      checkTargetGossipState( 8,  1,  3,  7, 11, false, {TargetFork.Fulu})
      checkTargetGossipState(10,  0,  5,  7, 11, false, {TargetFork.Fulu,   TargetFork.BPO1})
      checkTargetGossipState( 4,  0,  0,  4,  7,  true, default(set[TargetFork]))
      checkTargetGossipState( 0,  1,  2,  5,  9,  true, default(set[TargetFork]))
      checkTargetGossipState( 6,  2,  3, 10, 11,  true, default(set[TargetFork]))
      checkTargetGossipState( 5,  1,  5,  9, 10, false, {TargetFork.Electra})
      checkTargetGossipState(10,  3,  5,  7, 11, false, {TargetFork.Fulu,   TargetFork.BPO1})
      checkTargetGossipState( 3,  0,  1,  2,  5, false, {TargetFork.Fulu})
      checkTargetGossipState( 8,  0,  1,  7, 10, false, {TargetFork.Fulu})
      checkTargetGossipState( 2,  0,  5,  7, 11, false, {TargetFork.Deneb})
      checkTargetGossipState(11,  0,  1,  3, 11, false, {TargetFork.BPO1})
      checkTargetGossipState( 8,  5,  7,  8,  9, false, {TargetFork.Fulu,   TargetFork.BPO1})
      checkTargetGossipState( 0,  0,  0,  1, 11,  true, default(set[TargetFork]))
      checkTargetGossipState( 6,  1,  4,  5,  9, false, {TargetFork.Fulu})
      checkTargetGossipState( 8,  2,  4,  5,  8, false, {TargetFork.BPO1})
      checkTargetGossipState( 1,  5,  8,  9, 10, false, {TargetFork.Capella})
      checkTargetGossipState(10,  2,  5,  6,  9, false, {TargetFork.BPO1})
      checkTargetGossipState( 5,  1,  2,  5,  9, false, {TargetFork.Fulu})
      checkTargetGossipState(10,  1,  5,  6, 11, false, {TargetFork.Fulu,   TargetFork.BPO1})
      checkTargetGossipState( 5,  0,  0,  1,  4, false, {TargetFork.BPO1})
      checkTargetGossipState( 8,  0,  2,  5,  7, false, {TargetFork.BPO1})
      checkTargetGossipState( 7,  3,  4,  8, 10, false, {TargetFork.Electra,     TargetFork.Fulu})
      checkTargetGossipState( 9,  1,  6,  9, 10, false, {TargetFork.Fulu,   TargetFork.BPO1})
      checkTargetGossipState( 5,  4,  5,  7, 10, false, {TargetFork.Electra})
      checkTargetGossipState( 5,  2,  8,  9, 11, false, {TargetFork.Deneb})
      checkTargetGossipState( 0,  2,  4,  7, 10, false, {TargetFork.Capella})
      checkTargetGossipState(11,  1,  4,  9, 10, false, {TargetFork.BPO1})
      checkTargetGossipState( 4,  0,  6,  8, 10, false, {TargetFork.Deneb})
      checkTargetGossipState(10,  0,  1,  6, 10, false, {TargetFork.BPO1})
      checkTargetGossipState( 2,  0,  1,  3, 11, false, {TargetFork.Electra,     TargetFork.Fulu})
      checkTargetGossipState( 2,  2,  5,  6, 10, false, {TargetFork.Deneb})
      checkTargetGossipState( 1,  0,  4,  5,  8, false, {TargetFork.Deneb})
      checkTargetGossipState( 5,  0,  2,  3,  8, false, {TargetFork.Fulu})
      checkTargetGossipState( 2,  6,  7,  8,  9, false, {TargetFork.Capella})
      checkTargetGossipState( 2,  2,  4,  6,  7, false, {TargetFork.Deneb})
      checkTargetGossipState( 8,  2,  5,  6,  8, false, {TargetFork.BPO1})
      checkTargetGossipState( 4,  5,  8,  9, 10,  true, default(set[TargetFork]))
      checkTargetGossipState( 0,  0,  3,  5, 10, false, {TargetFork.Deneb})
      checkTargetGossipState( 8,  0,  1,  2,  4, false, {TargetFork.BPO1})
      checkTargetGossipState( 0,  5,  7,  9, 11, false, {TargetFork.Capella})
      checkTargetGossipState( 8,  1,  3,  6,  9, false, {TargetFork.Fulu,   TargetFork.BPO1})
      checkTargetGossipState( 1,  5,  6,  7,  8, false, {TargetFork.Capella})
      checkTargetGossipState( 5,  0,  5,  8, 11, false, {TargetFork.Electra})
      checkTargetGossipState( 0,  0,  2,  9, 11, false, {TargetFork.Deneb})
      checkTargetGossipState(10,  4,  6,  9, 10, false, {TargetFork.BPO1})
      checkTargetGossipState( 1,  5,  9, 10, 11, false, {TargetFork.Capella})
      checkTargetGossipState(10,  3,  5,  9, 10, false, {TargetFork.BPO1})
      checkTargetGossipState( 6,  0,  1,  2, 10, false, {TargetFork.Fulu})
      checkTargetGossipState( 2,  0,  5,  8,  9, false, {TargetFork.Deneb})
      checkTargetGossipState( 1,  1,  2,  8,  9, false, {TargetFork.Deneb,   TargetFork.Electra})
      checkTargetGossipState( 6,  4,  7,  9, 10, false, {TargetFork.Deneb,   TargetFork.Electra})
      checkTargetGossipState(10,  0,  1,  6,  8, false, {TargetFork.BPO1})
      checkTargetGossipState( 3,  5,  6,  9, 10, false, {TargetFork.Capella})
      checkTargetGossipState( 4,  0,  1,  6,  7, false, {TargetFork.Electra})
      checkTargetGossipState( 4,  1,  2,  5,  6, false, {TargetFork.Electra,     TargetFork.Fulu})
      checkTargetGossipState( 9,  0,  6,  9, 10, false, {TargetFork.Fulu,   TargetFork.BPO1})
      checkTargetGossipState(11,  0,  2,  5, 11, false, {TargetFork.BPO1})
      checkTargetGossipState( 2,  0,  2,  6,  9,  true, default(set[TargetFork]))
      checkTargetGossipState( 5,  1,  5, 10, 11, false, {TargetFork.Electra})
      checkTargetGossipState( 0,  0,  1,  5,  7, false, {TargetFork.Deneb,   TargetFork.Electra})
      checkTargetGossipState( 9,  4,  5,  6,  7,  true, default(set[TargetFork]))
      checkTargetGossipState( 6,  1,  2,  9, 10, false, {TargetFork.Electra})
      checkTargetGossipState( 6,  0,  3,  4,  8, false, {TargetFork.Fulu})
      checkTargetGossipState( 3,  1,  3, 10, 11, false, {TargetFork.Electra})
      checkTargetGossipState( 8,  0,  3,  5, 11, false, {TargetFork.Fulu})
      checkTargetGossipState( 2,  1,  2,  5,  9, false, {TargetFork.Electra})
      checkTargetGossipState( 2,  1,  3,  8, 10, false, {TargetFork.Deneb,   TargetFork.Electra})
      checkTargetGossipState( 2,  0,  3,  4,  7, false, {TargetFork.Deneb,   TargetFork.Electra})
      checkTargetGossipState(11,  4,  7,  8,  9, false, {TargetFork.BPO1})
      checkTargetGossipState( 4,  0,  2,  3,  9, false, {TargetFork.Fulu})
      checkTargetGossipState( 4,  1,  2,  8, 10,  true, default(set[TargetFork]))
      checkTargetGossipState( 6,  3,  5,  6, 11, false, {TargetFork.Fulu})
      checkTargetGossipState( 1,  3,  4,  9, 10,  true, default(set[TargetFork]))
      checkTargetGossipState( 7,  0,  4,  7, 11, false, {TargetFork.Fulu})
      checkTargetGossipState( 1,  0,  5,  7, 10, false, {TargetFork.Deneb})
      checkTargetGossipState( 7,  3,  4,  7,  8, false, {TargetFork.Fulu,   TargetFork.BPO1})
      checkTargetGossipState(10,  5,  7,  8,  9,  true, default(set[TargetFork]))
      checkTargetGossipState( 9,  1,  3,  4,  6, false, {TargetFork.BPO1})
      checkTargetGossipState( 9,  0,  1,  8, 10, false, {TargetFork.Fulu,   TargetFork.BPO1})
      checkTargetGossipState( 4,  0,  4,  7, 11,  true, default(set[TargetFork]))
      checkTargetGossipState( 3,  0,  2,  5, 11,  true, default(set[TargetFork]))
      checkTargetGossipState( 5,  1,  3,  7,  9, false, {TargetFork.Electra})
      checkTargetGossipState( 1,  2,  3,  8, 10, false, {TargetFork.Capella, TargetFork.Deneb})
      checkTargetGossipState( 6,  0,  4,  5, 10,  true, default(set[TargetFork]))
      checkTargetGossipState( 9,  0,  0,  4,  7, false, {TargetFork.BPO1})
      checkTargetGossipState( 7,  2,  3,  9, 10, false, {TargetFork.Electra})
      checkTargetGossipState( 2,  2,  4,  7,  9, false, {TargetFork.Deneb})
      checkTargetGossipState( 4,  1,  6,  9, 11, false, {TargetFork.Deneb})
      checkTargetGossipState( 8,  1,  2,  9, 11,  true, default(set[TargetFork]))
      checkTargetGossipState( 6,  1,  6,  7,  9, false, {TargetFork.Electra,     TargetFork.Fulu})
      checkTargetGossipState( 2,  2,  6,  9, 11, false, {TargetFork.Deneb})
      checkTargetGossipState( 6,  0,  1,  6, 10, false, {TargetFork.Fulu})
      checkTargetGossipState( 9,  1,  2,  5, 10, false, {TargetFork.Fulu,   TargetFork.BPO1})
      checkTargetGossipState( 6,  1,  2,  5, 11,  true, default(set[TargetFork]))
      checkTargetGossipState( 5,  3,  4,  8,  9, false, {TargetFork.Electra})
      checkTargetGossipState( 1,  0,  2,  5,  9, false, {TargetFork.Deneb,   TargetFork.Electra})
      checkTargetGossipState( 7,  1,  4,  9, 10, false, {TargetFork.Electra})
      checkTargetGossipState( 5,  0,  4,  7, 10, false, {TargetFork.Electra})
      checkTargetGossipState( 1,  4,  6,  8, 10, false, {TargetFork.Capella})
      checkTargetGossipState(11,  1,  2,  4,  8, false, {TargetFork.BPO1})
      checkTargetGossipState( 2,  6,  8,  9, 11, false, {TargetFork.Capella})
      checkTargetGossipState( 1,  0,  9, 10, 11, false, {TargetFork.Deneb})
      checkTargetGossipState( 9,  1,  2,  6,  9, false, {TargetFork.BPO1})
      checkTargetGossipState( 2,  1,  6,  8, 11,  true, default(set[TargetFork]))
      checkTargetGossipState( 6,  1,  4,  8, 11, false, {TargetFork.Electra})
      checkTargetGossipState( 5,  2,  3,  5,  8, false, {TargetFork.Fulu})
      checkTargetGossipState( 0,  1,  2,  3, 11, false, {TargetFork.Capella, TargetFork.Deneb})
      checkTargetGossipState( 4,  3,  6,  8,  9, false, {TargetFork.Deneb})
      checkTargetGossipState( 8,  0,  2,  4,  6, false, {TargetFork.BPO1})
      checkTargetGossipState(10,  0,  1,  6, 10,  true, default(set[TargetFork]))
      checkTargetGossipState( 3,  1,  9, 10, 11, false, {TargetFork.Deneb})
      checkTargetGossipState( 7,  2,  6,  8, 10, false, {TargetFork.Electra,     TargetFork.Fulu})
      checkTargetGossipState( 7,  2,  3,  7, 10, false, {TargetFork.Fulu})
      checkTargetGossipState(10,  5,  8,  9, 10, false, {TargetFork.BPO1})
      checkTargetGossipState(11,  3,  6,  9, 10, false, {TargetFork.BPO1})
      checkTargetGossipState( 8,  0,  0,  5, 11, false, {TargetFork.Fulu})
      checkTargetGossipState(10,  2,  6,  7, 11, false, {TargetFork.Fulu,   TargetFork.BPO1})
      checkTargetGossipState( 2,  2,  3,  5,  7, false, {TargetFork.Deneb,   TargetFork.Electra})
      checkTargetGossipState(10,  2,  7,  8, 10,  true, default(set[TargetFork]))
      checkTargetGossipState( 5,  0,  4,  5,  9,  true, default(set[TargetFork]))
      checkTargetGossipState( 5,  0,  1,  2,  3, false, {TargetFork.BPO1})
      checkTargetGossipState( 9,  1,  2,  3,  7, false, {TargetFork.BPO1})
      checkTargetGossipState( 1,  1,  3,  4, 10, false, {TargetFork.Deneb})
      checkTargetGossipState( 5,  0,  1,  3,  9, false, {TargetFork.Fulu})
      checkTargetGossipState( 9,  0,  4, 10, 11, false, {TargetFork.Electra,     TargetFork.Fulu})
      checkTargetGossipState( 4,  1,  5,  7, 11, false, {TargetFork.Deneb,   TargetFork.Electra})
      checkTargetGossipState( 4,  0,  1,  4,  7, false, {TargetFork.Fulu})
      checkTargetGossipState( 8,  5,  8, 10, 11, false, {TargetFork.Electra})
      checkTargetGossipState(11,  2,  3,  5,  7, false, {TargetFork.BPO1})
      checkTargetGossipState( 9,  6,  7,  9, 11, false, {TargetFork.Fulu})
      checkTargetGossipState( 8,  3,  4,  7, 11, false, {TargetFork.Fulu})
      checkTargetGossipState( 0,  1,  2,  3,  6, false, {TargetFork.Capella, TargetFork.Deneb})
      checkTargetGossipState( 0,  3,  4,  5,  9, false, {TargetFork.Capella})
      checkTargetGossipState( 5,  3,  6,  7,  9, false, {TargetFork.Deneb,   TargetFork.Electra})
      checkTargetGossipState( 5,  5,  7,  8, 11, false, {TargetFork.Deneb})
      checkTargetGossipState(10,  1,  3,  7,  9, false, {TargetFork.BPO1})
      checkTargetGossipState(11,  0,  3,  9, 10, false, {TargetFork.BPO1})
      checkTargetGossipState( 2,  0,  2,  3,  4,  true, default(set[TargetFork]))
      checkTargetGossipState( 1,  0,  1,  8,  9, false, {TargetFork.Electra})
      checkTargetGossipState( 6,  0,  6,  7,  8,  true, default(set[TargetFork]))
      checkTargetGossipState( 4,  0,  1,  4, 10, false, {TargetFork.Fulu})
      checkTargetGossipState(11,  4,  5,  7,  8, false, {TargetFork.BPO1})
      checkTargetGossipState( 1,  1,  4,  5,  9, false, {TargetFork.Deneb})
      checkTargetGossipState( 6,  0,  2,  4,  7,  true, default(set[TargetFork]))
      checkTargetGossipState( 6,  3,  8, 10, 11, false, {TargetFork.Deneb})
      checkTargetGossipState( 3,  0,  1,  7, 11, false, {TargetFork.Electra})
      checkTargetGossipState( 1,  0,  6,  9, 11, false, {TargetFork.Deneb})
      checkTargetGossipState( 7,  2,  4,  6, 10, false, {TargetFork.Fulu})
      checkTargetGossipState(10,  0,  3,  5,  8, false, {TargetFork.BPO1})
      checkTargetGossipState(10,  0,  5,  7,  8, false, {TargetFork.BPO1})
      checkTargetGossipState( 0,  2,  8,  9, 11, false, {TargetFork.Capella})
      checkTargetGossipState( 3,  0,  1,  5,  8, false, {TargetFork.Electra})
      checkTargetGossipState( 1,  0,  0,  3,  4, false, {TargetFork.Electra})
      checkTargetGossipState( 2,  2,  4,  5,  8, false, {TargetFork.Deneb})
      checkTargetGossipState( 6,  0,  0,  3,  8, false, {TargetFork.Fulu})
      checkTargetGossipState( 4,  0,  2,  5,  6,  true, default(set[TargetFork]))
      checkTargetGossipState( 2,  0,  2,  3,  5, false, {TargetFork.Electra,     TargetFork.Fulu})
      checkTargetGossipState( 8,  0,  5,  6, 11, false, {TargetFork.Fulu})
      checkTargetGossipState( 7,  0,  2,  5,  7, false, {TargetFork.BPO1})
      checkTargetGossipState(11,  1,  2,  5,  8, false, {TargetFork.BPO1})
      checkTargetGossipState(10,  0,  3,  6, 10, false, {TargetFork.BPO1})
      checkTargetGossipState( 9,  0,  0,  2,  8, false, {TargetFork.BPO1})
      checkTargetGossipState( 1,  1,  2,  7,  8, false, {TargetFork.Deneb,   TargetFork.Electra})
      checkTargetGossipState( 5,  0,  1,  2,  8, false, {TargetFork.Fulu})
      checkTargetGossipState( 5,  3,  6,  9, 11, false, {TargetFork.Deneb,   TargetFork.Electra})
      checkTargetGossipState( 4,  4,  5,  9, 10, false, {TargetFork.Deneb,   TargetFork.Electra})
      checkTargetGossipState( 1,  1,  5,  6,  7, false, {TargetFork.Deneb})
      checkTargetGossipState( 3,  0,  0,  4,  8, false, {TargetFork.Electra,     TargetFork.Fulu})
      checkTargetGossipState( 3,  0,  0,  1,  4, false, {TargetFork.Fulu,   TargetFork.BPO1})
      checkTargetGossipState( 2,  0,  2,  5,  8, false, {TargetFork.Electra})
      checkTargetGossipState( 1,  4,  7,  8, 10, false, {TargetFork.Capella})
      checkTargetGossipState( 6,  0,  3,  8,  9, false, {TargetFork.Electra})
      checkTargetGossipState( 9,  2,  3,  5,  6, false, {TargetFork.BPO1})
      checkTargetGossipState(11,  1,  6, 10, 11, false, {TargetFork.BPO1})
      checkTargetGossipState( 2,  1,  4,  7, 11, false, {TargetFork.Deneb})
      checkTargetGossipState( 8,  4,  5,  7,  9, false, {TargetFork.Fulu,   TargetFork.BPO1})
      checkTargetGossipState( 9,  1,  8, 10, 11, false, {TargetFork.Electra,     TargetFork.Fulu})
      checkTargetGossipState( 5,  0,  1,  4,  5, false, {TargetFork.BPO1})
      checkTargetGossipState( 0,  2,  7,  8, 11, false, {TargetFork.Capella})
      checkTargetGossipState( 7,  3,  6,  7,  8, false, {TargetFork.Fulu,   TargetFork.BPO1})
      checkTargetGossipState(10,  3,  4,  7, 10, false, {TargetFork.BPO1})
      checkTargetGossipState( 4,  2,  3,  5,  8, false, {TargetFork.Electra,     TargetFork.Fulu})
      checkTargetGossipState(11,  1,  2,  3,  9, false, {TargetFork.BPO1})
      checkTargetGossipState( 1,  2,  8,  9, 11, false, {TargetFork.Capella, TargetFork.Deneb})
      checkTargetGossipState( 1,  1,  5, 10, 11, false, {TargetFork.Deneb})
      checkTargetGossipState( 2,  2,  9, 10, 11, false, {TargetFork.Deneb})
      checkTargetGossipState(11,  0,  0,  1, 11, false, {TargetFork.BPO1})
      checkTargetGossipState( 8,  2,  4,  6, 11, false, {TargetFork.Fulu})
      checkTargetGossipState( 1,  0,  3,  5, 11, false, {TargetFork.Deneb})
      checkTargetGossipState( 2,  3,  4,  9, 11, false, {TargetFork.Capella, TargetFork.Deneb})
      checkTargetGossipState( 8,  1,  2,  4,  7, false, {TargetFork.BPO1})
      checkTargetGossipState( 0,  4,  5,  6,  7, false, {TargetFork.Capella})
      checkTargetGossipState( 5,  3,  7,  9, 10, false, {TargetFork.Deneb})
      checkTargetGossipState( 3,  0,  5,  6,  9, false, {TargetFork.Deneb})
      checkTargetGossipState(11,  4,  6,  9, 11, false, {TargetFork.BPO1})
      checkTargetGossipState( 6,  5,  8, 10, 11, false, {TargetFork.Deneb})
      checkTargetGossipState(11,  2,  3,  4,  5, false, {TargetFork.BPO1})
      checkTargetGossipState( 1,  3,  5,  6, 11, false, {TargetFork.Capella})
      checkTargetGossipState(11,  5,  6,  7, 10, false, {TargetFork.BPO1})
      checkTargetGossipState( 5,  2,  6,  8,  9, false, {TargetFork.Deneb,   TargetFork.Electra})
      checkTargetGossipState( 1,  1,  3,  6, 11, false, {TargetFork.Deneb})
      checkTargetGossipState( 6,  0,  0,  1,  3, false, {TargetFork.BPO1})
      checkTargetGossipState( 6,  2,  6,  8,  9, false, {TargetFork.Electra})
      checkTargetGossipState( 1,  3,  5,  6,  7, false, {TargetFork.Capella})
      checkTargetGossipState(10,  3,  4,  5,  8,  true, default(set[TargetFork]))
      checkTargetGossipState( 8,  3,  7,  8, 10, false, {TargetFork.Fulu})
      checkTargetGossipState( 5,  1,  3,  6, 10, false, {TargetFork.Electra,     TargetFork.Fulu})
      checkTargetGossipState( 1,  0,  1,  2,  7, false, {TargetFork.Electra,     TargetFork.Fulu})
      checkTargetGossipState( 0,  0,  5,  6,  8, false, {TargetFork.Deneb})
      checkTargetGossipState( 9,  2,  4,  5,  8,  true, default(set[TargetFork]))
      checkTargetGossipState( 1,  0,  0,  2, 10, false, {TargetFork.Electra,     TargetFork.Fulu})
      checkTargetGossipState( 3,  0,  3,  7,  8, false, {TargetFork.Electra})
      checkTargetGossipState(10,  2,  3,  5,  6, false, {TargetFork.BPO1})
      checkTargetGossipState( 5,  3,  6,  9, 10,  true, default(set[TargetFork]))
      checkTargetGossipState( 4,  2,  3,  8, 10, false, {TargetFork.Electra})
      checkTargetGossipState( 2,  1,  3, 10, 11, false, {TargetFork.Deneb,   TargetFork.Electra})
      checkTargetGossipState( 4,  0,  5,  7, 11, false, {TargetFork.Deneb,   TargetFork.Electra})
      checkTargetGossipState( 8,  2,  3,  7,  8,  true, default(set[TargetFork]))
      checkTargetGossipState( 8,  2,  4,  7,  9,  true, default(set[TargetFork]))
      checkTargetGossipState(10,  4,  5,  6,  8,  true, default(set[TargetFork]))
      checkTargetGossipState( 1,  1,  2,  8, 10, false, {TargetFork.Deneb,   TargetFork.Electra})
      checkTargetGossipState( 3,  5,  6,  8,  9,  true, default(set[TargetFork]))
      checkTargetGossipState( 7,  0,  0,  1,  6,  true, default(set[TargetFork]))
      checkTargetGossipState( 8,  0,  4,  5, 11, false, {TargetFork.Fulu})
      checkTargetGossipState( 2,  0,  6,  8,  9, false, {TargetFork.Deneb})
      checkTargetGossipState( 0,  1,  4,  8, 10, false, {TargetFork.Capella, TargetFork.Deneb})
      checkTargetGossipState(10,  0,  0,  0,  4, false, {TargetFork.BPO1})
      checkTargetGossipState( 9,  1,  3,  5,  9, false, {TargetFork.BPO1})
      checkTargetGossipState( 1,  1,  4, 10, 11,  true, default(set[TargetFork]))
      checkTargetGossipState(11,  1,  8,  9, 10, false, {TargetFork.BPO1})
      checkTargetGossipState( 2,  0,  1,  4,  5, false, {TargetFork.Electra})
      checkTargetGossipState( 3,  4,  8, 10, 11, false, {TargetFork.Capella, TargetFork.Deneb})
      checkTargetGossipState( 5,  7,  8,  9, 11, false, {TargetFork.Capella})
      checkTargetGossipState( 6,  0,  1,  3,  6, false, {TargetFork.BPO1})
      checkTargetGossipState(10,  0,  2,  6,  7, false, {TargetFork.BPO1})
      checkTargetGossipState( 3,  0,  5,  9, 10, false, {TargetFork.Deneb})
      checkTargetGossipState( 5,  0,  6,  7,  9, false, {TargetFork.Deneb,   TargetFork.Electra})
      checkTargetGossipState( 8,  6,  7,  8, 11, false, {TargetFork.Fulu})
      checkTargetGossipState( 2,  3,  4,  8, 11, false, {TargetFork.Capella, TargetFork.Deneb})
      checkTargetGossipState(10,  6,  7,  9, 11, false, {TargetFork.Fulu,   TargetFork.BPO1})
      checkTargetGossipState( 5,  1,  2,  8, 11, false, {TargetFork.Electra})
      checkTargetGossipState(10,  4,  7,  9, 10, false, {TargetFork.BPO1})
      checkTargetGossipState( 2,  0,  0,  2,  3, false, {TargetFork.Fulu,   TargetFork.BPO1})
      checkTargetGossipState( 6,  0,  5,  7,  8,  true, default(set[TargetFork]))
      checkTargetGossipState(10,  1,  2,  3,  8, false, {TargetFork.BPO1})
      checkTargetGossipState( 3,  3,  5,  7,  8,  true, default(set[TargetFork]))
      checkTargetGossipState( 7,  1,  2,  3,  6, false, {TargetFork.BPO1})
      checkTargetGossipState( 6,  3,  4,  7,  9, false, {TargetFork.Electra,     TargetFork.Fulu})
      checkTargetGossipState( 4,  0,  3, 10, 11, false, {TargetFork.Electra})
      checkTargetGossipState( 9,  0,  0,  0,  2, false, {TargetFork.BPO1})
      checkTargetGossipState( 5,  3,  6,  7, 11, false, {TargetFork.Deneb,   TargetFork.Electra})
      checkTargetGossipState( 9,  0,  2,  4,  6, false, {TargetFork.BPO1})
      checkTargetGossipState( 9,  1,  4,  9, 11, false, {TargetFork.Fulu})
      checkTargetGossipState( 6,  3,  5,  6, 10, false, {TargetFork.Fulu})
      checkTargetGossipState( 0,  4,  7,  9, 11, false, {TargetFork.Capella})
      checkTargetGossipState( 9,  0,  5,  8, 10, false, {TargetFork.Fulu,   TargetFork.BPO1})
      checkTargetGossipState( 5,  4,  5,  7,  9,  true, default(set[TargetFork]))
      checkTargetGossipState( 4,  0,  1,  2,  3, false, {TargetFork.BPO1})
      checkTargetGossipState( 4,  0,  2,  8, 10, false, {TargetFork.Electra})
      checkTargetGossipState(10,  0,  1,  4,  5, false, {TargetFork.BPO1})
      checkTargetGossipState( 0,  4,  5,  8,  9, false, {TargetFork.Capella})
      checkTargetGossipState( 7,  1,  3,  7, 11,  true, default(set[TargetFork]))
      checkTargetGossipState(11,  0,  1,  2, 10,  true, default(set[TargetFork]))
      checkTargetGossipState( 8,  1,  4,  8, 10,  true, default(set[TargetFork]))
      checkTargetGossipState( 2,  2,  3,  9, 11, false, {TargetFork.Deneb,   TargetFork.Electra})
      checkTargetGossipState( 3,  2,  6,  8,  9, false, {TargetFork.Deneb})
      checkTargetGossipState( 7,  0,  7,  8,  9, false, {TargetFork.Electra,     TargetFork.Fulu})
      checkTargetGossipState( 7,  0,  5,  6,  8, false, {TargetFork.Fulu,   TargetFork.BPO1})
      checkTargetGossipState( 9,  1,  9, 10, 11, false, {TargetFork.Electra,     TargetFork.Fulu})
      checkTargetGossipState( 9,  4,  5,  6, 11, false, {TargetFork.Fulu})
      checkTargetGossipState( 9,  1,  4,  6,  8,  true, default(set[TargetFork]))
      checkTargetGossipState( 4,  0,  3,  8,  9, false, {TargetFork.Electra})
      checkTargetGossipState( 0,  2,  3,  6, 10, false, {TargetFork.Capella})
      checkTargetGossipState( 9,  2,  4,  7, 11, false, {TargetFork.Fulu})
      checkTargetGossipState( 3,  0,  3,  7,  9, false, {TargetFork.Electra})
      checkTargetGossipState( 9,  1,  2,  3,  8,  true, default(set[TargetFork]))
      checkTargetGossipState( 0,  2,  3,  6,  8, false, {TargetFork.Capella})
      checkTargetGossipState( 7,  6,  9, 10, 11, false, {TargetFork.Deneb})
      checkTargetGossipState( 5,  1,  5,  8, 11,  true, default(set[TargetFork]))
      checkTargetGossipState( 4,  1,  2,  5, 11,  true, default(set[TargetFork]))
      checkTargetGossipState( 0,  4,  6, 10, 11, false, {TargetFork.Capella})
      checkTargetGossipState( 7,  3,  6,  9, 11, false, {TargetFork.Electra})
      checkTargetGossipState( 2,  0,  4,  6,  7, false, {TargetFork.Deneb})
      checkTargetGossipState( 8,  2,  4, 10, 11, false, {TargetFork.Electra})
      checkTargetGossipState( 4,  6,  7,  8, 10,  true, default(set[TargetFork]))
      checkTargetGossipState(11,  0,  1,  7,  8, false, {TargetFork.BPO1})
      checkTargetGossipState( 0,  1,  2,  3,  4, false, {TargetFork.Capella, TargetFork.Deneb})
      checkTargetGossipState( 3,  5,  6,  7,  9, false, {TargetFork.Capella})
      checkTargetGossipState( 8,  0,  2,  3,  5, false, {TargetFork.BPO1})
      checkTargetGossipState(11,  0,  6,  7,  8, false, {TargetFork.BPO1})
      checkTargetGossipState(10,  1,  2,  3, 10, false, {TargetFork.BPO1})
      checkTargetGossipState( 9,  1,  3,  6, 10,  true, default(set[TargetFork]))
      checkTargetGossipState( 0,  2,  7,  8,  9, false, {TargetFork.Capella})
      checkTargetGossipState( 2,  1,  2,  4, 11, false, {TargetFork.Electra})
      checkTargetGossipState( 6,  0,  2,  7,  8, false, {TargetFork.Electra,     TargetFork.Fulu})
      checkTargetGossipState( 0,  1,  6,  7,  9, false, {TargetFork.Capella, TargetFork.Deneb})
      checkTargetGossipState( 1,  5,  7,  9, 11, false, {TargetFork.Capella})
      checkTargetGossipState( 1,  1,  8,  9, 11, false, {TargetFork.Deneb})
      checkTargetGossipState( 9,  2,  6,  8, 11,  true, default(set[TargetFork]))
      checkTargetGossipState( 3,  0,  4,  8, 10, false, {TargetFork.Deneb,   TargetFork.Electra})
      checkTargetGossipState( 9,  2,  3,  9, 11, false, {TargetFork.Fulu})
      checkTargetGossipState( 6,  0,  1,  2,  6, false, {TargetFork.BPO1})
      checkTargetGossipState(11,  0,  3,  8, 10, false, {TargetFork.BPO1})
      checkTargetGossipState( 2,  2,  4,  5,  6, false, {TargetFork.Deneb})
      checkTargetGossipState( 1,  1,  3,  6,  8, false, {TargetFork.Deneb})
      checkTargetGossipState( 5,  1,  3,  6,  9, false, {TargetFork.Electra,     TargetFork.Fulu})
      checkTargetGossipState( 5,  1,  3,  6, 10,  true, default(set[TargetFork]))
      checkTargetGossipState( 3,  2,  3,  8, 11, false, {TargetFork.Electra})
      checkTargetGossipState( 2,  1,  2,  3, 10, false, {TargetFork.Electra,     TargetFork.Fulu})
      checkTargetGossipState( 3,  0,  1,  9, 10, false, {TargetFork.Electra})
      checkTargetGossipState( 0,  1,  3,  7,  9, false, {TargetFork.Capella, TargetFork.Deneb})
      checkTargetGossipState( 2,  3,  6, 10, 11, false, {TargetFork.Capella, TargetFork.Deneb})
      checkTargetGossipState( 2,  0,  4,  6,  9, false, {TargetFork.Deneb})
      checkTargetGossipState( 8,  0,  8,  9, 11, false, {TargetFork.Electra,     TargetFork.Fulu})
      checkTargetGossipState( 0,  0,  4,  6,  9, false, {TargetFork.Deneb})
      checkTargetGossipState(10,  1,  2,  3,  4, false, {TargetFork.BPO1})
      checkTargetGossipState( 4,  0,  3,  4,  7, false, {TargetFork.Fulu})
      checkTargetGossipState( 0,  2,  3,  8, 11, false, {TargetFork.Capella})
      checkTargetGossipState( 0,  3,  5,  7, 10,  true, default(set[TargetFork]))
      checkTargetGossipState( 9,  0,  0,  3,  7, false, {TargetFork.BPO1})
      checkTargetGossipState( 2,  1,  5,  6, 11, false, {TargetFork.Deneb})
      checkTargetGossipState(10,  2,  3,  6, 10, false, {TargetFork.BPO1})
      checkTargetGossipState( 5,  0,  4,  6, 11,  true, default(set[TargetFork]))
      checkTargetGossipState( 1,  1,  3,  4,  5, false, {TargetFork.Deneb})
      checkTargetGossipState(11,  1,  7,  8, 11,  true, default(set[TargetFork]))
      checkTargetGossipState( 3,  1,  5,  7,  9,  true, default(set[TargetFork]))
      checkTargetGossipState( 6,  0,  2,  5,  9, false, {TargetFork.Fulu})
      checkTargetGossipState( 4,  0,  1,  4,  9, false, {TargetFork.Fulu})
      checkTargetGossipState( 6,  4,  8,  9, 11,  true, default(set[TargetFork]))
      checkTargetGossipState(10,  0,  1,  2,  6, false, {TargetFork.BPO1})
      checkTargetGossipState(10,  1,  3,  7, 11, false, {TargetFork.Fulu,   TargetFork.BPO1})
      checkTargetGossipState( 3,  2,  5,  6,  7, false, {TargetFork.Deneb})
      checkTargetGossipState( 9,  4,  9, 10, 11, false, {TargetFork.Electra,     TargetFork.Fulu})
      checkTargetGossipState( 2,  2,  4,  9, 10, false, {TargetFork.Deneb})
      checkTargetGossipState( 8,  2,  4, 10, 11,  true, default(set[TargetFork]))
      checkTargetGossipState(11,  0,  8, 10, 11, false, {TargetFork.BPO1})
      checkTargetGossipState( 7,  0,  1,  7,  8, false, {TargetFork.Fulu,   TargetFork.BPO1})
      checkTargetGossipState( 4,  2,  8, 10, 11, false, {TargetFork.Deneb})
      checkTargetGossipState( 8,  5,  6,  8, 11, false, {TargetFork.Fulu})
      checkTargetGossipState( 8,  1,  5,  8, 11, false, {TargetFork.Fulu})
      checkTargetGossipState( 6,  1,  6,  7, 11, false, {TargetFork.Electra,     TargetFork.Fulu})
      checkTargetGossipState( 9,  3,  4,  5,  6, false, {TargetFork.BPO1})
      checkTargetGossipState( 1,  0,  3,  4,  7, false, {TargetFork.Deneb})
      checkTargetGossipState( 6,  1,  2,  3, 11, false, {TargetFork.Fulu})
      checkTargetGossipState( 1,  2,  5,  9, 10, false, {TargetFork.Capella, TargetFork.Deneb})
      checkTargetGossipState( 5,  0,  5,  7,  8, false, {TargetFork.Electra})
      checkTargetGossipState( 8,  0,  3, 10, 11, false, {TargetFork.Electra})
      checkTargetGossipState(11,  3,  6,  7,  8, false, {TargetFork.BPO1})
      checkTargetGossipState( 3,  6,  7,  9, 10,  true, default(set[TargetFork]))
      checkTargetGossipState( 7,  1,  6, 10, 11, false, {TargetFork.Electra})
      checkTargetGossipState( 0,  6,  9, 10, 11, false, {TargetFork.Capella})
      checkTargetGossipState( 4,  1,  2,  3,  5, false, {TargetFork.Fulu,   TargetFork.BPO1})
      checkTargetGossipState( 9,  1,  2,  7,  8, false, {TargetFork.BPO1})
