{
 "title": "NBC local testnet/sim (all nodes)",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(process_virtual_memory_bytes,node)"
   }
  ]
 },
 "panels": [
  {
   "title": "resources #${node}",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{node=\"${node}\"}[2s]) * 100",
     "legendFormat": "CPU usage %"
    },
    {
     "expr": "process_open_fds{node=\"${node}\"}",
     "legendFormat": "open file descriptors"
    },
    {
     "expr": "process_resident_memory_bytes{node=\"${node}\"}",
     "legendFormat": "RSS"
    },
    {
     "expr": "nim_gc_mem_bytes{node=\"${node}\"}",
     "legendFormat": "Nim GC mem total"
    },
    {
     "expr": "nim_gc_mem_occupied_bytes{node=\"${node}\"}",
     "legendFormat": "Nim GC mem used"
    }
   ]
  },
  {
   "title": "open streams #${node}",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libp2p_open_streams{node=\"${node}\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "validators #${node}",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "beacon_current_validators{node=\"${node}\"}",
     "legendFormat": "current validators"
    },
    {
     "expr": "beacon_current_live_validators{node=\"${node}\"}",
     "legendFormat": "current live validators"
    }
   ]
  },
  {
   "title": "GC heap objects #${node}",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nim_gc_heap_instance_occupied_bytes{node=\"${node}\"}",
     "legendFormat": "{{type_name}}"
    }
   ]
  },
  {
   "title": "pool.cachedStates #${node}",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "beacon_state_data_cache_hits_total{node=\"${node}\"} * 100 / (beacon_state_data_cache_hits_total{node=\"${node}\"} + beacon_state_data_cache_misses_total{node=\"${node}\"})",
     "legendFormat": "cache hit rate"
    }
   ]
  },
  {
   "title": "SQLite3 #${node}",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sqlite3_memory_used_bytes{node=\"${node}\"}",
     "legendFormat": "Memory used"
    }
   ]
  },
  {
   "title": "RSS mem #${node}",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 15 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_resident_memory_bytes{node=\"${node}\"}"
    }
   ]
  },
  {
   "title": "CPU usage #${node}",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 15 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{node=\"${node}\"}[2s]) * 100"
    }
   ]
  },
  {
   "title": "current slot #${node}",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "beacon_slot{node=\"${node}\"}"
    }
   ]
  },
  {
   "title": "att'ns sent #all",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 17, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(beacon_attestations_sent_total)"
    }
   ]
  },
  {
   "title": "att'ns recv'd #${node}",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "beacon_attestations_received_total{node=\"${node}\"}"
    }
   ]
  },
  {
   "title": "blocks #${node}",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_blocks_received_total{node=\"${node}\"}[4s]) * 3",
     "legendFormat": "received"
    },
    {
     "expr": "rate(beacon_blocks_proposed_total{node=\"${node}\"}[4s]) * 3",
     "legendFormat": "proposed"
    }
   ]
  },
  {
   "title": "current epoch #${node}",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "beacon_current_epoch{node=\"${node}\"}"
    }
   ]
  },
  {
   "title": "current justified epoch #${node}",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 17, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "beacon_current_justified_epoch{node=\"${node}\"}"
    }
   ]
  },
  {
   "title": "runtime #${node}",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 19 },
   "format": "dthms",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{node=\"${node}\"}"
    }
   ]
  },
  {
   "title": "libp2p peers #${node}",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "libp2p_peers{node=\"${node}\"}"
    }
   ]
  },
  {
   "title": "last finalized epoch #${node}",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 17, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "beacon_finalized_epoch{node=\"${node}\"}"
    }
   ]
  },
  {
   "title": "attestations #${node}",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_attestations_received_total{node=\"${node}\"}[4s]) * 3",
     "legendFormat": "received"
    },
    {
     "expr": "rate(beacon_attestations_sent_total{node=\"${node}\"}[4s]) * 3",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "received attestation delay (s) #${node}",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "rate(beacon_attestation_received_seconds_from_slot_start_bucket{node=\"${node}\"}[4s]) * 3",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Chronos: timers #${node}",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(chronos_loop_timers_total{node=\"${node}\"}[4s]) * 3",
     "legendFormat": "new timers/s"
    },
    { "expr": "chronos_loop_timers_queue", "legendFormat": "timers in queue" }
   ]
  },
  {
   "title": "Chronos: poll()/s #${node}",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(chronos_poll_ticks_total{node=\"${node}\"}[4s]) * 3",
     "legendFormat": "poll() calls/s"
    }
   ]
  },
  {
   "title": "Chronos: poll() duration (s) #${node}",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "rate(chronos_poll_duration_seconds_bucket{node=\"${node}\"}[4s]) * 3",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Chronos: events/s #${node}",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(chronos_poll_events_total{node=\"${node}\"}[4s]) * 3",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Chronos: new callbacks/s #${node}",
   "type": "graph",
   "gridPos": { "h": 15, "w": 14, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(chronos_future_callbacks_total{node=\"${node}\"}[4s]) * 3",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Chronos: processed callbacks/s #${node}",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(chronos_processed_callbacks_total{node=\"${node}\"}[4s]) * 3",
     "legendFormat": "processed cb/s"
    }
   ]
  },
  {
   "title": "Chronos: new futures/s #${node}",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(chronos_new_future_total{node=\"${node}\"}[4s]) * 3",
     "legendFormat": "new futures/s"
    }
   ]
  },
  {
   "title": "Chronos: pending futures #${node}",
   "type": "graph",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "chronos_pending_futures{node=\"${node}\"}",
     "legendFormat": "{{location}}"
    }
   ]
  }
 ]
}