{
 "title": "Nimbus Fleet Testnets",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(beacon_current_epoch{job=\"beacon-node-metrics\"},instance)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(beacon_current_epoch{job=\"beacon-node-metrics\",instance=\"${instance}\"},container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Validators",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "validators{instance=\"${instance}\",container=\"${container}\"}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nbc_peers{instance=\"${instance}\",container=\"${container}\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance=\"${instance}\",container=\"${container}\"}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval]) * 100"
    }
   ]
  },
  {
   "title": "RSS mem",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"${instance}\",container=\"${container}\"}"
    }
   ]
  },
  {
   "title": "version/network (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "version{instance=\"${instance}\",container=\"${container}\"}  ",
     "legendFormat": "{{version}}"
    },
    {
     "expr": "network_name{instance=\"${instance}\",container=\"${container}\"}  ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Wall slot",
   "type": "stat",
   "description": "Slot based on current wall clock time",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_slot{instance=\"${instance}\",container=\"${container}\"}"
    }
   ]
  },
  {
   "title": "Head slot",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_head_slot{instance=\"${instance}\",container=\"${container}\"}"
    }
   ]
  },
  {
   "title": "Wall epoch",
   "type": "stat",
   "description": "Epoch based on current wall clock time",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_slot{instance=\"${instance}\",container=\"${container}\"}/32"
    }
   ]
  },
  {
   "title": "Head epoch",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_head_slot{instance=\"${instance}\",container=\"${container}\"}/32"
    }
   ]
  },
  {
   "title": "Justified epoch",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_current_justified_epoch{instance=\"${instance}\",container=\"${container}\"}"
    }
   ]
  },
  {
   "title": "Finalized epoch",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_finalized_epoch{instance=\"${instance}\",container=\"${container}\"}"
    }
   ]
  },
  {
   "title": "resources (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval]) * 100",
     "legendFormat": "CPU usage %"
    },
    {
     "expr": "process_open_fds{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "open file descriptors"
    },
    {
     "expr": "process_resident_memory_bytes{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(nim_gc_mem_bytes{instance=\"${instance}\",container=\"${container}\"})",
     "legendFormat": "Nim GC mem total"
    },
    {
     "expr": "sum(nim_gc_mem_occupied_bytes{instance=\"${instance}\",container=\"${container}\"})",
     "legendFormat": "Nim GC mem used"
    }
   ]
  },
  {
   "title": "open streams (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "libp2p_open_streams{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "{{type}} ({{dir}})"
    }
   ]
  },
  {
   "title": "GC heap objects (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nim_gc_heap_instance_occupied_bytes{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "{{type_name}}"
    }
   ]
  },
  {
   "title": "peers (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "libp2p_peers{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "libp2p peers"
    },
    {
     "expr": "libp2p_pubsub_peers{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "libp2p pubsub peers"
    },
    {
     "expr": "nbc_peers{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "beacon_node peers"
    }
   ]
  },
  {
   "title": "blocks/slot (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(beacon_blocks_received_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval]) * 12",
     "legendFormat": "received"
    },
    {
     "expr": "rate(beacon_blocks_proposed_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval]) * 12",
     "legendFormat": "proposed"
    }
   ]
  },
  {
   "title": "peer type (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "libp2p_peers_identity{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "{{agent}}"
    }
   ]
  },
  {
   "title": "attestations/slot (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(beacon_attestations_received_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval]) * 12",
     "legendFormat": "received"
    },
    {
     "expr": "rate(beacon_attestations_sent_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval]) * 12",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "incoming traffic by peer type (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(libp2p_peers_traffic_read_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval])",
     "legendFormat": "{{agent}}"
    }
   ]
  },
  {
   "title": "aggregates/slot (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(beacon_aggregates_received_total{instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "sync committee msgs/slot (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(beacon_sync_committee_messages_received_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval])",
     "legendFormat": "messages"
    },
    {
     "expr": "rate(beacon_sync_committee_contributions_received_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval])",
     "legendFormat": "contributions"
    }
   ]
  },
  {
   "title": "outgoing traffic by peer type (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(libp2p_peers_traffic_write_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval])",
     "legendFormat": "{{agent}}"
    }
   ]
  },
  {
   "title": "dropped msgs/slot (ignored/rejected) (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(beacon_blocks_dropped_total{instance=\"${instance}\",container=\"${container}\",reason=\"Ignore\"}[$__rate_interval])",
     "legendFormat": "blocks (I)"
    },
    {
     "expr": "rate(beacon_attestations_dropped_total{instance=\"${instance}\",container=\"${container}\",reason=\"Ignore\"}[$__rate_interval])",
     "legendFormat": "attestations (I)"
    },
    {
     "expr": "rate(beacon_aggregates_dropped_total{instance=\"${instance}\",container=\"${container}\",reason=\"Ignore\"}[$__rate_interval])",
     "legendFormat": "aggregates (I)"
    },
    {
     "expr": "rate(beacon_sync_committee_messages_dropped_total{instance=\"${instance}\",container=\"${container}\",reason=\"Ignore\"}[$__rate_interval])",
     "legendFormat": "sync_msgs (I)"
    },
    {
     "expr": "rate(beacon_sync_committee_contributions_dropped_total{instance=\"${instance}\",container=\"${container}\",reason=\"Ignore\"}[$__rate_interval])",
     "legendFormat": "sync_contribs (I)"
    },
    {
     "expr": "rate(beacon_blocks_dropped_total{instance=\"${instance}\",container=\"${container}\",reason=\"Reject\"}[$__rate_interval])",
     "legendFormat": "blocks (R)"
    },
    {
     "expr": "rate(beacon_aggregates_dropped_total{instance=\"${instance}\",container=\"${container}\",reason=\"Reject\"}[$__rate_interval])",
     "legendFormat": "aggregates (R)"
    },
    {
     "expr": "rate(beacon_attestations_dropped_total{instance=\"${instance}\",container=\"${container}\",reason=\"Reject\"}[$__rate_interval])",
     "legendFormat": "attestations (R)"
    },
    {
     "expr": "rate(beacon_sync_committee_messages_dropped_total{instance=\"${instance}\",container=\"${container}\",reason=\"Reject\"}[$__rate_interval])",
     "legendFormat": "sync_msgs (R)"
    },
    {
     "expr": "rate(beacon_sync_committee_contributions_dropped_total{instance=\"${instance}\",container=\"${container}\",reason=\"Reject\"}[$__rate_interval])",
     "legendFormat": "sync_contribs (R)"
    }
   ]
  },
  {
   "title": "Mesh health",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "libp2p_gossipsub_healthy_peers_topics{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "healthy"
    },
    {
     "expr": "libp2p_gossipsub_low_peers_topics{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "low"
    },
    {
     "expr": "libp2p_gossipsub_no_peers_topics{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "no_peers"
    }
   ]
  },
  {
   "title": "validator rewards / epoch (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(attached_validator_balance_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval]) * 384 / 1000000000",
     "legendFormat": "GWei"
    }
   ]
  },
  {
   "title": "Fanout health",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "nbc_gossipsub_healthy_fanout{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "healthy"
    },
    {
     "expr": "nbc_gossipsub_good_fanout{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "good"
    },
    {
     "expr": "nbc_gossipsub_low_fanout{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "low"
    }
   ]
  },
  {
   "title": "Eth1 Chain Length",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "eth1_chain_len{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "eth1_chain_len"
    }
   ]
  },
  {
   "title": "Discovery & Dialing",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(libp2p_total_dial_attempts_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval])",
     "legendFormat": "Dial attempts"
    },
    {
     "expr": "rate(discovery_message_requests_outgoing_total{instance=\"${instance}\",container=\"${container}\",response!=\"no_response\"}[$__rate_interval])",
     "legendFormat": "Discovery messages"
    },
    {
     "expr": "rate(libp2p_successful_dials_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval])",
     "legendFormat": "Dial success"
    },
    {
     "expr": "rate(nbc_cycling_kicked_peers_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval])",
     "legendFormat": "Kicked peers"
    }
   ]
  },
  {
   "title": "SQLite3 (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sqlite3_memory_used_bytes{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "Memory used"
    }
   ]
  },
  {
   "title": "validators (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "beacon_active_validators{instance=\"${instance}\",container=\"${container}\"}",
     "legendFormat": "current validators"
    }
   ]
  },
  {
   "title": "Disk QOps Average",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "netdata_disk_qops_operations_average{instance=\"${instance}\"}",
     "legendFormat": "{{chart}}"
    }
   ]
  },
  {
   "title": "pool.cachedStates (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(beacon_state_data_cache_hits_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval]) / (rate(beacon_state_data_cache_misses_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval]) + rate(beacon_state_data_cache_hits_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval]))",
     "legendFormat": "cache hit rate"
    },
    {
     "expr": "rate(beacon_state_data_cache_misses_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval]) * 12  ",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Disk I/O Ops per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "netdata_disk_ops_operations_persec_average{instance=\"${instance}\"}",
     "legendFormat": "{{chart}}"
    }
   ]
  },
  {
   "title": "Batch verifications/slot (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(batch_verification_batches_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval])",
     "legendFormat": "batches"
    },
    {
     "expr": "rate(batch_verification_signatures_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval])",
     "legendFormat": "signatures"
    },
    {
     "expr": "rate(batch_verification_aggregates_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval])",
     "legendFormat": "aggregates"
    },
    {
     "expr": "rate(batch_verification_signatures_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval]) /\nrate(batch_verification_aggregates_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval])",
     "legendFormat": "sigs per agg"
    },
    {
     "expr": "rate(batch_verification_signatures_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval]) /\nrate(batch_verification_batches_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval])",
     "legendFormat": "sigs per batch"
    }
   ]
  },
  {
   "title": "Disk Backlog",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "netdata_disk_backlog_milliseconds_average{instance=\"${instance}\"}",
     "legendFormat": "{{chart}}"
    },
    {
     "expr": "netdata_disk_qops_operations_average{instance=\"${instance}\"}",
     "legendFormat": "{{chart}}"
    }
   ]
  },
  {
   "title": "att'ns sent #all",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(beacon_attestations_sent_total)"
    }
   ]
  },
  {
   "title": "att'ns recv'd",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_attestations_received_total{instance=\"${instance}\",container=\"${container}\"}"
    }
   ]
  },
  { "title": "Validator monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Produced block",
   "type": "stat",
   "description": "Number of blocks monitored validators produced in previous epoch",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_monitor_beacon_block_total{instance=\"${instance}\",container=\"${container}\"})"
    }
   ]
  },
  {
   "title": "Active",
   "type": "stat",
   "description": "Number of active validators being monitored that should be attesting",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_monitor_active{instance=\"${instance}\",container=\"${container}\"})"
    }
   ]
  },
  {
   "title": "Exited",
   "type": "stat",
   "description": "Validators that have exited from the chain, either volunt",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_monitor_exited{instance=\"${instance}\",container=\"${container}\"})"
    }
   ]
  },
  {
   "title": "Slashed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_monitor_slashed{instance=\"${instance}\",container=\"${container}\"})"
    }
   ]
  },
  {
   "title": "Withdrawable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_monitor_slashed{instance=\"${instance}\",container=\"${container}\"})"
    }
   ]
  },
  {
   "title": "CurrentSync",
   "type": "stat",
   "description": "Number of monitored validators in the current sync committee",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_monitor_validator_in_current_sync_committee{instance=\"${instance}\",container=\"${container}\"})"
    }
   ]
  },
  {
   "title": "NextSync",
   "type": "stat",
   "description": "Number of monitored validators in the next sync committee",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_monitor_validator_in_next_sync_committee{instance=\"${instance}\",container=\"${container}\"})"
    }
   ]
  },
  {
   "title": "Monitored",
   "type": "stat",
   "description": "Number of validators being monitored",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_monitor_active{instance=\"${instance}\",container=\"${container}\"})"
    }
   ]
  },
  {
   "title": "Attested",
   "type": "stat",
   "description": "Number of attestations monitored validators produced in previous epoch",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_monitor_prev_epoch_attestations_total{instance=\"${instance}\",container=\"${container}\"})"
    }
   ]
  },
  {
   "title": "Aggregated",
   "type": "stat",
   "description": "Number of aggregates monitored validators produced in previous epoch",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_monitor_prev_epoch_aggregates_total{instance=\"${instance}\",container=\"${container}\"})"
    }
   ]
  },
  {
   "title": "SyncMessaged",
   "type": "stat",
   "description": "Number of sync  messages monitored validators produced in previous epoch",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_monitor_prev_epoch_sync_committee_messages_total{instance=\"${instance}\",container=\"${container}\"})"
    }
   ]
  },
  {
   "title": "SyncContributed",
   "type": "stat",
   "description": "Number of sync  comntributions monitored validators produced in previous epoch",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_monitor_prev_epoch_sync_contributions_total{instance=\"${instance}\",container=\"${container}\"})"
    }
   ]
  },
  {
   "title": "Aggregate inclusions",
   "type": "stat",
   "description": "Number of times attestation produced by monitored validator was seen in an aggregate",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_monitor_prev_epoch_attestation_aggregate_inclusions{instance=\"${instance}\",container=\"${container}\"})"
    }
   ]
  },
  {
   "title": "Block inclusions",
   "type": "stat",
   "description": "Number of times attestation was seen in a block",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_monitor_prev_epoch_attestation_block_inclusions{instance=\"${instance}\",container=\"${container}\"})"
    }
   ]
  },
  {
   "title": "Attestation misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(validator_monitor_prev_epoch_on_chain_head_attester_miss_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval]))*384",
     "legendFormat": "head"
    },
    {
     "expr": "sum(rate(validator_monitor_prev_epoch_on_chain_target_attester_miss_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval]))*384",
     "legendFormat": "target"
    },
    {
     "expr": "sum(rate(validator_monitor_prev_epoch_on_chain_source_attester_miss_total{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval]))*384",
     "legendFormat": "source"
    }
   ]
  },
  {
   "title": "Balance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance, container) (rate(validator_monitor_balance_gwei{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval]) / on(instance,container) validator_monitor_validators_total{instance=\"${instance}\",container=\"${container}\"})",
     "legendFormat": "balance"
    }
   ]
  },
  {
   "title": "Block & Attestation Delays (slow)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 },
   "collapsed": true,
   "panels": [
    {
     "title": "received attestation delay (s) (${instance})",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 92 },
     "targets": [
      {
       "expr": "rate(beacon_attestation_delay_bucket{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval])",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "received beacon block delay (s) (${instance})",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 92 },
     "targets": [
      {
       "expr": "rate(beacon_block_delay_bucket{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval])",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "received aggregate delay (s) (${instance})",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 98 },
     "targets": [
      {
       "expr": "rate(beacon_aggregate_delay_bucket{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval])",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "storeBlock() duration (s) (${instance})",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 98 },
     "targets": [
      {
       "expr": "rate(beacon_store_block_duration_seconds_bucket{instance=\"${instance}\",container=\"${container}\"}[$__rate_interval])",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}