#!/bin/sh

set -e

( systemctl is-active --quiet nimbus_validator_client.service && \
  echo "Nimbus has been upgraded, don't forget to restart with 'sudo systemctl restart nimbus_validator_client.service'!" ) || true
