# beacon_chain
# Copyright (c) 2020-2025 Status Research & Development GmbH
# Licensed and distributed under either of
#   * MIT license (license terms in the root directory or at https://opensource.org/licenses/MIT).
#   * Apache v2 license (license terms in the root directory or at https://www.apache.org/licenses/LICENSE-2.0).
# at your option. This file may not be copied, modified, or distributed except according to those terms.

name: CI
on:
  push:
    paths-ignore: ['media/**', 'docs/**', '**/*.md']
    branches:
      - stable
      - testing
      - unstable
  pull_request:
    paths-ignore: ['media/**', 'docs/**', '**/*.md']
    branches-ignore:
      - stable
  workflow_dispatch:

concurrency: # Cancel stale PR builds (but not push builds)
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - os: linux
            cpu: amd64
          - os: macos
            cpu: arm64
          - os: windows
            cpu: amd64
        branch: [~, upstream/version-2-2]
        exclude:
          - target:
              os: macos
            branch: upstream/version-2-2
          - target:
              os: windows
            branch: upstream/version-2-2
        include:
          - branch: upstream/version-2-2
            branch-short: version-2-2
            nimflags-extra: --mm:refc
          - target:
              os: linux
            builder: ['self-hosted','ubuntu-22.04']
          - target:
              os: macos
              cpu: arm64
            builder: macos-latest
          - target:
              os: windows
            builder: windows-2022

    defaults:
      run:
        shell: bash

    name: ${{ matrix.target.os }}-${{ matrix.target.cpu }}${{ matrix.branch != '' && ' (Nim ' || '' }}${{ matrix.branch-short }}${{ matrix.branch != '' && ')' || '' }}
    runs-on: ${{ matrix.builder }}

    steps:
      - name: Fix nim cache conflicts
        run: |
          echo "XDG_CACHE_HOME=${{ runner.temp }}/.nim-cache" >> $GITHUB_ENV
          echo "CI_CACHE=${{ runner.temp }}/.nbs-cache" >> $GITHUB_ENV

      - name: Clean workspace (very aggressive)
        if: contains(matrix.builder, 'self-hosted')
        run: rm -rf "$GITHUB_WORKSPACE"/*

      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore llvm-mingw (Windows) from cache
        if: runner.os == 'Windows'
        id: windows-mingw-cache
        uses: actions/cache@v4
        with:
          path: external/mingw-${{ matrix.target.cpu }}
          key: 'mingw-llvm-17-${{ matrix.target.cpu }}'

      - name: Install llvm-mingw dependency (Windows)
        if: >
          steps.windows-mingw-cache.outputs.cache-hit != 'true' &&
          runner.os == 'Windows'
        run: |
          mkdir -p external
          MINGW_BASE="https://github.com/mstorsjo/llvm-mingw/releases/download/20230905"
          MINGW_URL="$MINGW_BASE/llvm-mingw-20230905-ucrt-x86_64.zip"
          curl -L "$MINGW_URL" -o "external/mingw-${{ matrix.target.cpu }}.zip"
          7z x -y "external/mingw-${{ matrix.target.cpu }}.zip" -oexternal/mingw-${{ matrix.target.cpu }}/
          mv external/mingw-${{ matrix.target.cpu }}/**/* ./external/mingw-${{ matrix.target.cpu }}

      - name: Path to cached dependencies (Windows)
        if: >
          runner.os == 'Windows'
        run: |
          echo '${{ github.workspace }}'"/external/mingw-${{ matrix.target.cpu }}/bin" >> $GITHUB_PATH
          echo "${{ github.workspace }}/external/dlls-${{ matrix.target.cpu }}" >> $GITHUB_PATH
          # for miniupnp that runs "wingenminiupnpcstrings.exe" from the current dir
          echo "." >> $GITHUB_PATH

      - name: Derive environment variables
        run: |
          if [[ '${{ matrix.target.cpu }}' == 'amd64' ]]; then
            PLATFORM=x64
          elif [[ '${{ matrix.target.cpu }}' == 'arm64' ]]; then
            PLATFORM=arm64
          else
            PLATFORM=x86
          fi
          echo "PLATFORM=$PLATFORM" >> $GITHUB_ENV

          # Stack usage test and UBSAN on recent enough gcc:
          if [[ '${{ runner.os }}' == 'Linux' && '${{ matrix.target.cpu }}' == 'amd64' ]]; then
            if [[ '${{ github.sha }}' =~ ^7 ]]; then
              export WITH_UBSAN=1
              echo "WITH_UBSAN=1" >> $GITHUB_ENV
              export NIMFLAGS="${NIMFLAGS} -d:limitStackUsage --passC:-fsanitize=undefined --passL:-fsanitize=undefined"
            else
              export NIMFLAGS="${NIMFLAGS} -d:limitStackUsage"
            fi
          fi

          if [[ '${{ runner.os }}' == 'Windows' ]]; then
            export NIMFLAGS="${NIMFLAGS} --cc:clang"
          fi

          export NIMFLAGS="${NIMFLAGS} ${{ matrix.nimflags-extra }}"
          echo "NIMFLAGS=${NIMFLAGS}" >> $GITHUB_ENV

          ncpu=""
          make_cmd="make"
          case '${{ runner.os }}' in
          'Linux')
            ncpu=$(nproc)
            ;;
          'macOS')
            ncpu=$(sysctl -n hw.ncpu)
            ;;
          'Windows')
            ncpu=${NUMBER_OF_PROCESSORS}
            make_cmd="mingw32-make"
            echo "Number of cores: ${NUMBER_OF_PROCESSORS}"
            echo "Physical memory: $(wmic ComputerSystem get TotalPhysicalMemory)"
            echo "Partition sizes: $(wmic partition get name,size,type)"
            ;;
          esac
          [[ -z "$ncpu" || $ncpu -le 0 ]] && ncpu=1
          echo "ncpu=${ncpu}" >> $GITHUB_ENV
          echo "make_cmd=${make_cmd}" >> $GITHUB_ENV

      - name: Get latest nimbus-build-system commit hash
        id: versions
        shell: bash
        run: |
          nbsHash=$(git rev-parse HEAD:vendor/nimbus-build-system)
          echo "nimbus_build_system=$nbsHash" >> $GITHUB_OUTPUT

      - name: Restore prebuilt Nim from cache
        if: matrix.branch == null
        id: nim-cache
        uses: actions/cache@v4
        with:
          path: NimBinCache
          key: 'nim-${{ matrix.target.os }}-${{ matrix.target.cpu }}-${{ steps.versions.outputs.nimbus_build_system }}'

      - name: Build Nim and Nimbus dependencies
        run: |
          ${make_cmd} -j ${ncpu} NIM_COMMIT=${{ matrix.branch }} ARCH_OVERRIDE=${PLATFORM} QUICK_AND_DIRTY_COMPILER=1 CI_CACHE=NimBinCache update
          ./env.sh nim --version

      - name: Build binaries (with trace logging enabled)
        run: |
          ${make_cmd} -j ${ncpu} V=1 NIM_COMMIT=${{ matrix.branch }} LOG_LEVEL=TRACE NIMFLAGS="-u:release --opt:none ${NIMFLAGS}"
          # The Windows image runs out of disk space, so make some room
          rm -rf build nimcache

      # Important: even with a cache hit, this should be run
      # as it symlinks the cached items in their proper place
      - name: Get the Ethereum Foundation fixtures
        run: |
          scripts/setup_scenarios.sh fixturesCache

      - name: Run tests
        run: |
          ${make_cmd} -j ${ncpu} V=1 NIM_COMMIT=${{ matrix.branch }} DISABLE_TEST_FIXTURES_SCRIPT=1 test

      # The upload creates a combined report that gets posted as a comment on the PR
      # https://github.com/EnricoMi/publish-unit-test-result-action
      - name: Upload combined results
        uses: actions/upload-artifact@v4
        with:
          # upload-artifact requires avoiding "/", because "To maintain file
          # system agnostic behavior, these characters are intentionally not
          # allowed to prevent potential problems with downloads on different
          # file systems". However, GitHub Actions workflows do not support a
          # usual assortment of string functions.
          name: Unit Test Results ${{ matrix.target.os }}-${{ matrix.target.cpu }}-${{ matrix.branch == 'upstream/version-2-2' && 'version-2-2' || matrix.branch }}
          path: build/*.xml

  devbuild:
    name: "Developer builds"
    runs-on: ['self-hosted','ubuntu-22.04']
    steps:
      - name: Fix nim cache conflicts
        run: |
          echo "XDG_CACHE_HOME=${{ runner.temp }}/.nim-cache" >> $GITHUB_ENV
          echo "CI_CACHE=${{ runner.temp }}/.nbs-cache" >> $GITHUB_ENV

      - name: Clean workspace (very aggressive)
        run: rm -rf "$GITHUB_WORKSPACE"/*

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build files with isMainModule
        run: |
          makefile_content=$(<./Makefile)
          executables=()
          while IFS= read -r file; do
              base=$(basename "$file" ".nim")
              if ! grep -qw "$base" <<< "$makefile_content"; then
                  executables+=("$file")
              fi
          done < <(grep -Rl --include="*.nim" --exclude-dir=vendor "when isMainModule:" .)
          make -j update
          source env.sh
          for executable in "${executables[@]}"; do
            nim c --passC:-fsyntax-only --noLinking:on -d:chronicles_log_level=TRACE "${executable}"
          done

  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # In PR, has extra merge commit: ^1 = PR, ^2 = base
          submodules: 'recursive'

      - name: Check copyright year
        if: ${{ !cancelled() }} && github.event_name == 'pull_request'
        run: |
          excluded_files="config.yaml|config.nims|beacon_chain.nimble|Makefile|Product.wxs"
          excluded_extensions="ans|bin|cfg|yml|json|json\\.template|md|png|service|ssz|tpl|txt|lock|nix|gitignore|envrc|sh"

          current_year=$(date +"%Y")
          problematic_files=()
          while read -r file; do
            if ! grep -qE 'Copyright \(c\) .*'$current_year' Status Research & Development GmbH' "$file"; then
              problematic_files+=("$file")
            fi
          done < <(git diff --name-only --diff-filter=AM --ignore-submodules HEAD^ HEAD | grep -vE '(\.('$excluded_extensions')|'$excluded_files')$' || true)

          if (( ${#problematic_files[@]} )); then
            echo "The following files do not have an up-to-date copyright year:"
            for file in "${problematic_files[@]}"; do
              echo "- $file"
            done
            exit 2
          fi

      - name: Check exception tracking
        if: ${{ !cancelled() }} && github.event_name == 'pull_request'
        run: |
          scripts/check_exception_headers.sh
      - name: Check submodules
        if: ${{ !cancelled() }} && github.event_name == 'pull_request'
        run: |
          scripts/check_submodule_branches.sh

  # https://github.com/EnricoMi/publish-unit-test-result-action
  event_file:
    name: "Event File"
    runs-on: ubuntu-latest
    steps:
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Event File
          path: ${{ github.event_path }}
